# Generated by Django 5.0.8 on 2026-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_product_updated_at_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
