# Generated by Django 5.0.8 on 2026-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
